version: '3.8'
services: 
  app:
    container_name: compass
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - '27017:27017'
    volumes:
      - ~/.mongodb/data/db:/data/db
  rabbitmq:
    image: rabbitmq:3.8.14-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
